# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.service.template_user_data:
        class: AppBundle\Service\TemplateUserData
        arguments:
            - ['@security.token_storage']
            - '@repository.league_has_user'
    repository.league_has_user:
        class: Doctrine\ORM\EntityRepository
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments:
            - AppBundle\Entity\LeagueHasUser
