services:
    repository.league_has_user:
        class: Doctrine\ORM\EntityRepository
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments:
            - AppBundle\Entity\LeagueHasUser

    repository.pick:
        class: Doctrine\ORM\EntityRepository
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments:
            - AppBundle\Entity\Pick

    repository.match:
        class: Doctrine\ORM\EntityRepository
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments:
            - AppBundle\Entity\Match

    repository.statistics:
        class: Doctrine\ORM\EntityRepository
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments:
            - AppBundle\Entity\Statistics

    repository.player:
        class: Doctrine\ORM\EntityRepository
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments:
            - AppBundle\Entity\Player

    repository.league:
        class: Doctrine\ORM\EntityRepository
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments:
            - AppBundle\Entity\League